Refactoring1
JungDaewook/Todo-JavaScript pull request #10
Opened 2022-04-18 15:10 UTC by JungDaewook

modifyThatImissed 브랜치에서 받은 코멘트들이 리팩토링 관련 코멘트들이라 새로운 브랜치를 생성해서 코멘트를 해결했어요.

2022-04-18 15:36 UTC, unpo88 requested changes
@JungDaewook 

남겨진 코멘트들 확인 부탁드립니다 🙏

2022-04-18 15:36 UTC, unpo88 commented on .vscode/launch.json
> +}
@JungDaewook 

요 코드는 어떻게 들어간건지 설명이 필요합니다~

2022-04-18 15:36 UTC, unpo88 commented on Todo_List.html
> +    <input type = 'text' id = 'todoInputText' />
@JungDaewook 

`maxlength`가 빠졌는데 왜 빠지게 된것일까요?

2022-04-18 15:36 UTC, unpo88 commented on addTodoItem.js
> +    const todoInputText = document.getElementById('todoInputText').value;
@JungDaewook 

여기서는 아래 코드를 재사용할 수는 없는 것일까요?
``` javascript
function getTodoInputTextValue() {
  return document.getElementById('todoInputText').value;
}
```

2022-04-18 15:36 UTC, unpo88 commented on functionsOfTodoList.js
> +}
@JungDaewook 

해당 코드를 재사용해야한다면 함수의 위치는 어디에 위치하는 것이 적절할까요?

2022-04-18 15:36 UTC, unpo88 commented on addTodoItem.js
> +    const todoInputText = document.getElementById('todoInputText').value;
@JungDaewook 

`addTodoItem.js `를 분리하였는데, 해당 코드가 `functionsOfTodoList.js`에서도 사용되는 것 같은데

이렇게 구성된 이유는 무엇일까요?

2022-04-18 15:36 UTC, unpo88 commented on functionsOfTodoList.js
> +  }*/
@JungDaewook 

해당 코드는 왜 주석처리를 하였을까요?

사용하지 않는 코드라면 제거하는것이 좋을 것 같습니다

2022-04-18 15:36 UTC, unpo88 commented on functionsOfTodoList.js
> +  TODO_ITEM_COUNT++;
@JungDaewook 

엇! 암쏘리! 생각해보니까 `TODO_ITEM_COUNT`는 상수가 아니라, 변수에 가깝네요!

`todoItemCount` 라는 네이밍으로 다시 변경해야할 것 같습니다 🙏

2022-04-18 15:36 UTC, unpo88 commented on functionsOfTodoList.js
> +function removeTodoItem(TODO_ITEM_COUNT) {
@JungDaewook 

`removeTodoItem`에서 `TODO_ITEM_COUNT`라는 사실을 알아야할 이유가 있을까요? 🤔 

`removeTodoItem` 에서 받아오는 파라미터의 값은 사실상 생성된 `todoItem`의 `id`값을 찾기 위한 속성이지 않나요?

그렇다면, `removeTodoItem`을 호출하는 곳에서 `todoItem + TODO_ITEM_COUNT`을 파라미터로 넘기고

`removeTodoItem`의 정의를 다음과 같이 변경하면 조금 더 직관적이지 않을까요?

``` javascript
function removeTodoItem(todoItemId){
   const deleteTodoItem = document.getElementById(todoItemId)
   ...
}
```

2022-04-18 15:36 UTC, unpo88 commented on functionsOfTodoList.js
> +  if (getTodoInputTextValue() === EMPTY_TODO_INPUT_TEXT){
@JungDaewook 

`EMPTY_TODO_INPUT_TEXT`는 상수가 아니고, 빈 문자열을 나타내기 때문에 `''` 라는 표현을 그대로 사용하는것이 좋을 것 같습니다. 

`EMPTY_TODO_INPUT_TEXT`라는 상수명은 한 번 더 생각하게 되기 때문에, `''`라는 표현을 직관적으로 사용하는 것이 가독성에 더 도움이 될 것 같아요.

2022-04-18 15:36 UTC, unpo88 commented on functionsOfTodoList.js
> +function isBiggerThanMAX_TODO_ITEM_COUNT(){
@JungDaewook 

변수 네이밍이 `camelCase`과 `snake_case` 가 혼용되서 사용되는 것 같아요.

이렇게 사용한 이유가 있을까요?

2022-04-23 23:40 UTC, JungDaewook commented
> @JungDaewook
> 
> 남겨진 코멘트들 확인 부탁드립니다 🙏

[답변/파일 제거 완료 및 주석 제거]
https://github.com/JungDaewook/Todo-JavaScript/pull/10/commits/dc77dd9218391b4b1927c6024c3a40becee150aa
위 커밋에서 디버깅을 위해 생성했던 파일과 의도치 않게 생성된 addTodoItem.js 파일을 제거했고, 주석처리 된 코드를 삭제했어요.

2022-04-23 23:54 UTC, JungDaewook commented
>@JungDaewook

>엇! 암쏘리! 생각해보니까 TODO_ITEM_COUNT는 상수가 아니라, 변수에 가깝네요!

>todoItemCount 라는 네이밍으로 다시 변경해야할 것 같습니다 🙏

[답변/수정완료]
https://github.com/JungDaewook/Todo-JavaScript/pull/10/commits/4e198f29cc30f95e162991a8de0c6dd97c303b3b
위 커밋에서 수정 완료했습니다.

2022-04-23 23:56 UTC, JungDaewook commented
@JungDaewook

EMPTY_TODO_INPUT_TEXT는 상수가 아니고, 빈 문자열을 나타내기 때문에 '' 라는 표현을 그대로 사용하는것이 좋을 것 같습니다.

EMPTY_TODO_INPUT_TEXT라는 상수명은 한 번 더 생각하게 되기 때문에, ''라는 표현을 직관적으로 사용하는 것이 가독성에 더 도움이 될 것 같아요.

[답변/수정완료]
https://github.com/JungDaewook/Todo-JavaScript/pull/10/commits/51de47d94a554a1c6e381b5827b0a57ec3ef45aa
위 커밋에서 수정완료했습니다.

2022-04-23 23:57 UTC, JungDaewook commented
@JungDaewook

변수 네이밍이 camelCase과 snake_case 가 혼용되서 사용되는 것 같아요.

이렇게 사용한 이유가 있을까요?

[답변/반영 후 수정완료]
https://github.com/JungDaewook/TodoJavaScript/pull/10/commits/a8072007dcb96424b1b920e9a33c65be6ffa69f6
혼용한 이유는 변수면이 snake case라 혼용했는데 가독성이 떨어지는 것 같아서 camelcase로 변경했습니다.

2022-04-24 00:03 UTC, JungDaewook commented
@JungDaewook

maxlength가 빠졌는데 왜 빠지게 된것일까요?

[답변/수정완료]
https://github.com/JungDaewook/Todo-JavaScript/pull/10/commits/077de7dc4cdb7f5f70e6cb5751d58f62391c484c
확인해보니 의도치 않게 modifyThatImissed 브랜치에서도 빠져 있어서 다시 추가했어요.

2022-04-24 12:18 UTC, unpo88 requested changes
@JungDaewook 

처리가 아직 안된 코멘트는 살펴봐주시면 좋을 것 같아요.

그리고 제가 달아놓은 코멘트에 대한 답글은, 해당 코멘트에 답글로 달아주세요 🙏 

각각의 답변이 모두 파편화되어있어서 살펴보기 어렵습니다.

---------------------------

추가로 Conflict 나는 부분도 확인해주세요~

2022-04-24 12:25 UTC, unpo88 commented on functionsOfTodoList.js
> +  }
@JungDaewook 

``` javascript
function isEmptyTodoInputText(){
  if (getTodoInputTextValue() === ''){
    alert("입력창에 할 일을 입력하십시오.");
    return true;
  }
  return false;
}
```

함수명을 살펴보면 `is~` 과 같은 네이밍으로 `boolean`을 반환할 것 처럼 보이지만
🤔 내부를 보면 `alert` 도 호출하고 있어서 SRP원칙에 위배되지 않을까요?

해당 코드를 아래와 같이 변경한다면 SRP 원칙을 위배하지 않고 구현할 수 있지 않을까요?

``` javascript
function isEmptyTodoInputText(){
  if (getTodoInputTextValue() === ''){
    return true;
  }
  return false;
}

function isBiggerThanMaxTodoItemCount(){
  if (todoItemCount >= MAX_TODO_ITEM_COUNT){
    return true;
  }
  return false;
}

function handleAddButton(){
  if(isEmptyTodoInputText()) {
    alert("입력창에 할 일을 입력하십시오.");
  }

  if(isBiggerThanMaxTodoItemCount()){
    alert("할 일은 20개까지만 입력할 수 있습니다.");
  }
  
  if(!isEmptyTodoInputText() && !isBiggerThanMaxTodoItemCount()){
    addTodoItem();
  }
```

2022-04-29 17:03 UTC, JungDaewook commented
> @JungDaewook
> 
> 처리가 아직 안된 코멘트는 살펴봐주시면 좋을 것 같아요.
> 
> 그리고 제가 달아놓은 코멘트에 대한 답글은, 해당 코멘트에 답글로 달아주세요 🙏
> 
> 각각의 답변이 모두 파편화되어있어서 살펴보기 어렵습니다.
> 
> 추가로 Conflict 나는 부분도 확인해주세요~

[답변/conflick 해결]
죄송해요. 다음부터는 코멘트에 quote reply 버튼을 눌러서 달도록 할게요!
추가적으로 conflict는 modifyThatImissed branch에서 handleAddButton() 함수가 추가되지 않아서 발생했었는데 web editor를 통해서 해결했어요.

2022-04-30 00:11 UTC, JungDaewook commented
[모든 코멘트 처리 완료/ merge?]
이제 모든 코멘트들을 다 처리한 것 같은데 추가적으로 코멘트하실 부분이 있으면 남겨주시고 없으시다면 merge해보도록 할게요!

2022-05-01 13:04 UTC, unpo88 commented
> [모든 코멘트 처리 완료/ merge?] 이제 모든 코멘트들을 다 처리한 것 같은데 추가적으로 코멘트하실 부분이 있으면 남겨주시고 없으시다면 merge해보도록 할게요!

@JungDaewook 

1. 아직 남겨진 코멘트에 답변이 안달린 것들이 있어요.
2. Conflict 해결이 안되었어요.

확인 부탁드립니다 🙏

2022-05-01 13:05 UTC, unpo88 requested changes
코멘트 확인해주세요~

2022-05-01 13:07 UTC, unpo88 requested changes
@JungDaewook 

추가로 남겨놓은 코멘트도 확인해주세용~

2022-05-01 13:07 UTC, unpo88 commented on functionsOfTodoList.js
> +  return false;
@JungDaewook 

``` javascript
return todoItemCount >= MAX_TODO_ITEM_COUNT
```

다음과 같은 조건문으로도 코드의 라인을 줄일 수 있지 않을까요~?

2022-05-01 13:07 UTC, unpo88 commented on functionsOfTodoList.js
> +  return false;
@JungDaewook 

아래 한 줄로 코드를 줄일 수 있지 않을까요~?
``` javascript
return getTodoInputTextValue() === ''
```

2022-05-02 18:21 UTC, merged

2022-05-02 18:32 UTC, JungDaewook commented
[실수로 pr이 자동 close가 됨]
앗 죄송해요. 제가 refactoring1에서 작업하던 것들을 그대로 modifyThatImissed로 끌고 들어가서 이어서 작업을 하려고 modifyThatImissed 브랜치에서 refactoring1을 pull한 다음 제가 하려던 작업을 하고 push를 했는데 이 pr이 자동으로 close 되는 상황이 발생해버렸어요.