마지막 요구사항 strike 기능 구현 완료!
JungDaewook/Todo-JavaScript pull request #12
Opened 2022-05-20 15:24 UTC by JungDaewook

마지막 요구사항인 strick기능 구현 완료!
1. todoItem을 todoList에 추가할 때 완료 버튼이 생성되도록 수정
2. removeTodoItem 함수를 참고하여 strikeTodoItem 함수 생성

2022-05-20 15:46 UTC, unpo88 commented
@JungDaewook 

`완료` 버튼을 누르면 `완료` 버튼은 `취소` 버튼으로 변경되고

`취소` 버튼을 다시 누르면 `완료` 버튼이 보임과 동시에 `strike`가 취소되는 처리를 추가해보는 것은 어떠한가요?

2022-05-20 15:46 UTC, unpo88 requested changes
@JungDaewook 

코멘트 남겨놓은것 하나 확인 부탁드립니다 🙏

2022-05-29 11:42 UTC, JungDaewook commented
> 코멘트에 따라 완료 버튼과 취소 버튼 구현 완료!



> @JungDaewook
> 
> `완료` 버튼을 누르면 `완료` 버튼은 `취소` 버튼으로 변경되고
> 
> `취소` 버튼을 다시 누르면 `완료` 버튼이 보임과 동시에 `strike`가 취소되는 처리를 추가해보는 것은 어떠한가요?

[제안 반영]
https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/6de1bdee163a7e628943c09ad4657e838003b270
위 커밋으로 요구사항 구현 완료!

2022-05-29 11:54 UTC, JungDaewook commented on functionsOfTodoList.js
> +  clickStrikeButton.setAttribute("onclick", 'cancelStrikeTodoItem(\''+todoItemId+'\')');
[겪었던 어려움과 해결방법]
`clickSrikeButton.setAttribute("onclick", 'cancelStrikeTodoItem("todoItemId");`
이었던 기존 코드에서 위의 코드와 같이 변경함. setAttribute라는 함수에서 onclick에 들어갈 함수를 변경하는 과정에서 그 파라미터를 문자열인 "todoItemId"로 바꾸는 실수를 범하였고 debugger;를 통해서 그 사실을 발견. 함수 파라미터를 넘길 때 어떻게 넘겨야 하는지 구글링 후 해결!

2022-05-29 11:55 UTC, JungDaewook commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "&nbsp; <input type = 'button' id = 'strikeButton' onclick = 'strikeTodoItem(\""+todoItemId+"\")' value = '완료'/> <button type = 'button' onclick = 'removeTodoItem(\""+todoItem
strikeTodoItem 함수와 cancelStrikeTodoItem 함수에서 .value, setAttribute 를 활용하기 위해 button type 이었던 strikeButton을 input type으로 변경

2022-05-29 11:55 UTC, JungDaewook commented on functionsOfTodoList.js
> +let beforeStrikeTodoItem = "";
취소 버튼을 누르면 초기의 todoItem으로 초기화해주기 위해 beforeStrikeTodoItem이라는 문자열 변수 생성

2022-05-29 11:57 UTC, JungDaewook commented
[추가 구현 예정]
![스크린샷 2022-05-28 오전 8.08.31.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/63d5644d-5635-4fc3-8f27-0fc1087efa5e/스크린샷_2022-05-28_오전_8.08.31.png)

2022-05-29 11:58 UTC, JungDaewook commented
<img width="175" alt="스크린샷 2022-05-29 오후 8 58 12" src="https://user-images.githubusercontent.com/40848888/170866871-6621b43e-2705-494d-9535-87276ba1248d.png">

2022-05-29 14:03 UTC, JungDaewook commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "&nbsp; <input type = 'button' id = 'strikeButton' onclick = 'strikeTodoItem(\""+todoItemId+"\")' value = '완료'/> <input type = 'button' onclick = 'removeTodoItem(\""+todoItemI
strikeTodoItem 함수에서 버튼에는 strike 처리가 되지 않도록 하려고 innerHTML 에서 innerText로 변경하였고, text 값을 없애주기 위해서 삭제 버튼의 input type도 button type으로 변경했어요.

2022-05-29 14:05 UTC, JungDaewook commented on functionsOfTodoList.js
> +  strikeTodoItem.innerHTML = "<strike>" + strikeTodoItem.innerText + "</strike> <input type = 'button' id = 'strikeButton' onclick = 'cancelStrikeTodoItem(\""+todoItemId+"\")' value = '취소'/> <input t
innerHTML 대신 innerText 를 사용함으써 Text값만 변경할 수 있었고 뒤에 취소버튼과 삭제 버튼을 추가함으로써 위에 과정을 생략할 수 있었어요.

2022-05-29 14:06 UTC, JungDaewook commented on functionsOfTodoList.js
> +  //clickStrikeButton.setAttribute("onclick", 'cancelStrikeTodoItem(\''+todoItemId+'\')');
[실수/삭제완료]
구현하는 과정에서 생긴 주석 3줄을 실수로 add 해버려서
1e6ad2eb484cf84795d45bc73793e289dea09fba
위 커밋에서 삭제했어요. 미안해요.

2022-05-29 14:08 UTC, JungDaewook commented
> <img alt="스크린샷 2022-05-29 오후 8 58 12" width="175" src="https://user-images.githubusercontent.com/40848888/170866871-6621b43e-2705-494d-9535-87276ba1248d.png">
> 
> [추가 해결 예정] todoItem의 텍스트뿐만 아니라 버튼의 뒤쪽에 strike처리가 되는 현상 해결 예정이에요.

[해결완료]
https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/2c05445be979f83352938bd9b4f31a44e336d9c8
위 커밋으로 해결했어요.

2022-05-30 14:15 UTC, JungDaewook commented
> @JungDaewook
> 
> 코멘트 남겨놓은것 하나 확인 부탁드립니다 🙏

확인완료했습니다!

2022-05-30 14:18 UTC, JungDaewook commented
test

2022-06-06 05:09 UTC, unpo88 commented
@JungDaewook 

정상동작하지 않는 경우가 있네요~
확인 부탁드립니다 🙏 

https://user-images.githubusercontent.com/14287771/172098564-de4a1ae5-d4cb-43d0-97f8-4068851fc958.mov

2022-06-06 05:29 UTC, unpo88 requested changes
@JungDaewook 

기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏

2022-06-08 05:09 UTC, JungDaewook commented
> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏



> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏
[해결 완료]
[0f49702](https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/0f49702bfdd9620b856891e7ff7ee51e4bd6bf49)[0f49702](https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/0f49702bfdd9620b856891e7ff7ee51e4bd6bf49)
위 커밋으로 해결완료했습니다.

2022-06-08 05:09 UTC, JungDaewook commented
> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏



> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏
[해결 완료]
[0f49702](https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/0f49702bfdd9620b856891e7ff7ee51e4bd6bf49)[0f49702](https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/0f49702bfdd9620b856891e7ff7ee51e4bd6bf49)
위 커밋으로 해결완료했습니다.

2022-06-08 05:15 UTC, JungDaewook commented
> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏



> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏

[해결완료]
[0f49702](https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/0f49702bfdd9620b856891e7ff7ee51e4bd6bf49)
위 커밋으로 해결완료했어요.

[문제 원인]
전역으로 선언된 beforeTodoItem 에서
두 개의 todoItem에 완료 버튼을 누른 상태에서 마지막으로 완료버튼을 누른 todoItem이 아닌 다른 todoItem의 취소 버튼을 눌렀을 때 완료 버튼을 마지막으로 누른 todoItem의 innerHTML 값이 beforeTodoItem에 저장되어 다른 todoItem의 취소 버튼을 누르면 잘못된 todoItem의 innerText 값이 들어가는 현상이 발생했고 
이를 beforeTodoItem 이라는 변수를 삭제하고 함수 내용을 수정하여 해결했어요.

2022-06-08 05:15 UTC, JungDaewook commented
> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏



> @JungDaewook
> 
> 기능 동작 오류가 있어서 해결하면 다시 리퀘스트 부탁드립니다 🙏

[해결완료]
[0f49702](https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/0f49702bfdd9620b856891e7ff7ee51e4bd6bf49)
위 커밋으로 해결완료했어요.

[문제 원인]
전역으로 선언된 beforeTodoItem 에서
두 개의 todoItem에 완료 버튼을 누른 상태에서 마지막으로 완료버튼을 누른 todoItem이 아닌 다른 todoItem의 취소 버튼을 눌렀을 때 완료 버튼을 마지막으로 누른 todoItem의 innerHTML 값이 beforeTodoItem에 저장되어 다른 todoItem의 취소 버튼을 누르면 잘못된 todoItem의 innerText 값이 들어가는 현상이 발생했고 
이를 beforeTodoItem 이라는 변수를 삭제하고 함수 내용을 수정하여 해결했어요.

2022-06-08 05:15 UTC, JungDaewook commented on functionsOfTodoList.js
> -let beforeStrikeTodoItem = "";
오류를 발생시키는 beforeStrikeTodoItem 변수 삭제

2022-06-08 05:15 UTC, JungDaewook commented on functionsOfTodoList.js
> -let beforeStrikeTodoItem = "";
오류를 발생시키는 beforeStrikeTodoItem 변수 삭제

2022-06-08 05:16 UTC, JungDaewook commented on functionsOfTodoList.js
>  }
불필요한 변수와 코드 제거

2022-06-08 05:16 UTC, JungDaewook commented on functionsOfTodoList.js
>  }
불필요한 변수와 코드 제거

2022-06-08 05:16 UTC, JungDaewook commented on functionsOfTodoList.js
> +  cancelStrikeTodoItem.innerHTML = cancelStrikeTodoItem.innerText + "<input type = 'button' id = 'strikeButton' onclick = 'strikeTodoItem(\""+todoItemId+"\")' value = '완료'/> <input type = 'button' on
innerText 함수는 <strike></strike> 태그를 포함하지 않는다는 것을 깨닫고 코드 구현.

2022-06-08 05:16 UTC, JungDaewook commented on functionsOfTodoList.js
> +  cancelStrikeTodoItem.innerHTML = cancelStrikeTodoItem.innerText + "<input type = 'button' id = 'strikeButton' onclick = 'strikeTodoItem(\""+todoItemId+"\")' value = '완료'/> <input type = 'button' on
innerText 함수는 <strike></strike> 태그를 포함하지 않는다는 것을 깨닫고 코드 구현.

2022-06-08 15:57 UTC, JungDaewook commented
https://github.com/JungDaewook/Todo-JavaScript/pull/12/commits/5ae9f866361f954f4b4b392ed2d1581f2a191fa5
[리팩터링]
가독성을 위해 innerHTML 코드를 여러 줄로 구별.

2022-06-17 01:00 UTC, unpo88 approved these changes
LGTM!

2022-06-17 03:23 UTC, merged