Refactoring2
JungDaewook/Todo-JavaScript pull request #13
Opened 2022-06-24 12:44 UTC by JungDaewook

branch 목적 : 기능적 오류 수정 및 리팩토링
수정 사항 : todoItemIdCount라는 변수를 생성하여 기능적 오류를 수정.
겪었던 문제점  : main에서 수정해버리는 바람에 main과 compare 했을 때 pr이 생성되지 않아서 base를 수정 전 main 과 동일했던 strikeTodoItem 브랜치로 설정.

2022-06-24 12:48 UTC, JungDaewook commented
[기능적 오류]
3개의 todoitem을 추가한 뒤 가운데 것을 삭제하고 다시 todoitem을 추가하면 세번째 것을 완료했을 때 두번째 것이 완료가 되는 문제 발생.

원인 
   todoItemCount가 삭제 버튼을 눌러서 removeTodoItem 함수가 실행됐을 때 1이 줄어드는데 그러고 나서 또 항목을 추가하면 같은 todoItemId를 가진 항목들이 두 개가 생긴다. 같은 todoItemId를 가진 더 밑에 있는 항목을 완료 버튼을 눌렀을 때 같은 todoItemId를 가진 위의 항목이 완료처리가 됐던 것.

해결방법 
   todoItemId의 값이 항목의 개수를 나타내는 todoItemCount 변수가 아닌 고유한 값의 변수가 있어야겠다고 판단해서 todoItemIdCount 라는 변수를 새로 생성하여 todoItemCount 대신 쓰고, todoItemCount는 단순하게 항목의 개수를 세는 용도로만 사용하도록 수정하였다.

겪었던 문제점
   main에서 수정해버리는 바람에 main과 compare 했을 때 pr이 생성되지 않아서 base를 수정 전 main 과 동일했던 strikeTodoItem 브랜치로 설정.

2022-06-26 13:40 UTC, unpo88 requested changes
@JungDaewook 

코멘트 남겨놓았습니다.

확인 부탁드립니다 🙇 

---------------------------

추가로 현재 PR의 [Description](https://github.com/JungDaewook/Todo-JavaScript/pull/13#issue-1283707697)과 남겨주신 [코멘트](https://github.com/JungDaewook/Todo-JavaScript/pull/13#issuecomment-1165541529)들을 읽었을 때 리뷰어 입장에서 가독성이 좋은 것 처럼 느껴지지 않아요.

제가 가독성이 높은 것 처럼 느껴지지 않는 이유는 다음과 같아요.

- PR의 제목을 보고 어떠한 작업을 했는지 유추하기 어려움
- PR의 Description에 있는 정보가 리뷰를 하는데 있어서 어떤 유용함을 주는 것인지 파악하기 어려움
  - 리뷰어로서 어떤 리뷰를 드리면 좋을지에 대한 정보가 기재되어 있지 않음
  - 다른 곳에서는 PR Description에 어떻게 기재하고 있을까요?
  - PR을 더 잘 요청하기 위해서 어떠한 정보들을 습득하면 좋을까요?
- 코멘트에 남겨진 대부분의 문장이 서술형으로 되어있어서 원하는 정보를 한 눈에 파악하기 어려움
  - `기능적 오류`, `원인`, `해결방법`, `겪었던 문제점` 카테고라이징은 되어있으나, 서술형 문장으로 구성
  - 두괄식 표현을 사용해보는 것은 어떠한가요~?

추가로 @JungDaewook 이 읽어보면 좋을만한 책과 강의를 추천하겠습니다.
1. [일 잘하는 사람은 단순하게 말합니다.](http://www.yes24.com/Product/Goods/90164296)
2. [일 잘하는 사람은 단순하게 합니다](http://www.yes24.com/Product/Goods/70922866)
3. [독서는 '일'이어야만 한다](https://www.youtube.com/watch?v=tSlGJmlWw0I)

2022-06-26 13:40 UTC, unpo88 commented on functionsOfTodoList.js
>  let todoItemCount = 0;
@JungDaewook 

`todoItemCount` 변수와 `todoItemIdCount` 변수는 헷갈릴 여지가 없을까요~?

가독성을 더 높이려면 어떤 변수명이 어울릴까요?

2022-06-26 13:40 UTC, unpo88 commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "<input type = 'button' onclick = 'removeTodoItem(\""+todoItemId+"\")' value = '삭제\'/>";
@JungDaewook 

라인의 맨 끝에 `\` 문자가 추가된 이유는 무엇인가요~?

2022-06-29 13:37 UTC, JungDaewook commented
> @JungDaewook
> 
> 코멘트 남겨놓았습니다.
> 
> 확인 부탁드립니다 🙇
> 
> 추가로 현재 PR의 [Description](https://github.com/JungDaewook/Todo-JavaScript/pull/13#issue-1283707697)과 남겨주신 [코멘트](https://github.com/JungDaewook/Todo-JavaScript/pull/13#issuecomment-1165541529)들을 읽었을 때 리뷰어 입장에서 가독성이 좋은 것 처럼 느껴지지 않아요.
> 
> 제가 가독성이 높은 것 처럼 느껴지지 않는 이유는 다음과 같아요.
> 
> * PR의 제목을 보고 어떠한 작업을 했는지 유추하기 어려움
> * PR의 Description에 있는 정보가 리뷰를 하는데 있어서 어떤 유용함을 주는 것인지 파악하기 어려움
>   
>   * 리뷰어로서 어떤 리뷰를 드리면 좋을지에 대한 정보가 기재되어 있지 않음
>   * 다른 곳에서는 PR Description에 어떻게 기재하고 있을까요?
>   * PR을 더 잘 요청하기 위해서 어떠한 정보들을 습득하면 좋을까요?
> * 코멘트에 남겨진 대부분의 문장이 서술형으로 되어있어서 원하는 정보를 한 눈에 파악하기 어려움
>   
>   * `기능적 오류`, `원인`, `해결방법`, `겪었던 문제점` 카테고라이징은 되어있으나, 서술형 문장으로 구성
>   * 두괄식 표현을 사용해보는 것은 어떠한가요~?
> 
> 추가로 @JungDaewook 이 읽어보면 좋을만한 책과 강의를 추천하겠습니다.
> 
> 1. [일 잘하는 사람은 단순하게 말합니다.](http://www.yes24.com/Product/Goods/90164296)
> 2. [일 잘하는 사람은 단순하게 합니다](http://www.yes24.com/Product/Goods/70922866)
> 3. [독서는 '일'이어야만 한다](https://www.youtube.com/watch?v=tSlGJmlWw0I)

[코멘트 반영]
코멘트들을 더 보기 좋게 수정해 봤어요.

2022-07-01 15:52 UTC, unpo88 commented on functionsOfTodoList.js
>  let todoItemCount = 0;
@JungDaewook 

코멘트가 대응이 된 것인지 이야기가 안되어있어서 코멘트에 답변으로 남겨주면

해당 사항이 반영이 된 것인지 아닌지를 판단할 수 있을 것 같아요.

제가 모두 확인하는 것이 비효율적이라는 생각이 들어서요.

2022-07-01 15:52 UTC, unpo88 commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "<input type = 'button' onclick = 'removeTodoItem(\""+todoItemId+"\")' value = '삭제\'/>";
@JungDaewook 

코멘트가 대응이 된 것인지 이야기가 안되어있어서 해당 코멘트에 답변으로 남겨주면

해당 사항이 반영이 된 것인지 아닌지를 판단할 수 있을 것 같아요.

제가 모두 확인하는 것이 비효율적이라는 생각이 들어서요.

2022-07-01 15:54 UTC, unpo88 approved these changes
@JungDaewook 

코멘트 추가로 남겨놓았는데, 모두 확인 후 반영해서 Merge 진행해주세요~

2022-07-01 15:54 UTC, unpo88 commented on functionsOfTodoList.js
> +let todoItemIdNumber = 0;
@JungDaewook 

`todoItemIdNumber` 보다는 `todoItemIdIndex`가 조금 더 어울릴 것 같아요 👍 

왜 `Index`가 더 어울릴 것 같은지는 조사를 해보면 좋을 것 같습니다!

2022-07-01 16:08 UTC, JungDaewook commented on functionsOfTodoList.js
> +  let todoItemId = "todoItem" + todoItemIdCount;
[고유한 todoItemId를 표현하기 위한 변수 생성 / todoItemCount 변수 목적 변경 / 모호한 두 변수 사이의 네이밍 질문]
-todoItemIdCount라는 변수를 생성하여 todoItem을 삭제해도 줄어들지 않는 고유한 ID 값 표현.
-todoItemCount는 todoItemId라는 변수에 더해지는 것이 아니라 그냥 todoItem의 개수를 세는 용도로 변경.
-todoItemCount 와 todoItemIdCount라는 변수명이 모호하여 더 나은 네이밍이 없는지 고려 중.

2022-07-01 16:08 UTC, JungDaewook commented on functionsOfTodoList.js
>  let todoItemCount = 0;
https://github.com/JungDaewook/Todo-JavaScript/pull/13/commits/b84ffbf7e30c8f5a6c34d32b38f7320ae8a71d1a

[코멘트 반영]
저 또한 그렇게 생각하고 있어서 무슨 이름이 좋을까 고민하다가 위 커밋을 통해
todoItemIdCount -> todoItemIdNumber 로 바꿔봤어요.

2022-07-01 16:08 UTC, JungDaewook commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "<input type = 'button' onclick = 'removeTodoItem(\""+todoItemId+"\")' value = '삭제\'/>";
https://github.com/JungDaewook/Todo-JavaScript/pull/13/commits/54424ed7b3ea1ee6f3c51577a4f854075d488409

[코멘트 반영/디버깅 실수 삭제]
디버깅을 하는 과정에서 삭제 버튼 뒤에 todoItemCount를 띄웠었는데 그 과정에서 생긴 실수 같아요. 위 커밋으로 삭제했으며 다음에는 push 전에 반드시 확인하도록 할게요.

2022-07-01 16:08 UTC, JungDaewook commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "<input type = 'button' onclick = 'removeTodoItem(\""+todoItemId+"\")' value = '삭제\'/>";
https://github.com/JungDaewook/Todo-JavaScript/pull/13#issuecomment-1165541529

2022-07-06 10:44 UTC, JungDaewook commented on functionsOfTodoList.js
> +let todoItemIdNumber = 0;
> @JungDaewook
> 
> `todoItemIdNumber` 보다는 `todoItemIdIndex`가 조금 더 어울릴 것 같아요 👍
> 
> 왜 `Index`가 더 어울릴 것 같은지는 조사를 해보면 좋을 것 같습니다!

https://github.com/JungDaewook/Todo-JavaScript/pull/13/commits/521a298af1e7e2f4c134ef5127f31d64b9a4e431
[코멘트 반영]
변수 네이밍에서 Count, Number는 개수를 셀 때 사용하고, Index는 원하는 값을 찾아갈 때 사용하는데, 변수의 사용 이유가 삭제, 완료이므로 후자의 목적이 맞다고 생각하여 변수명을 변경했어요.

2022-07-06 10:45 UTC, merged