Style without layout of todo list
JungDaewook/Todo-JavaScript pull request #16
Opened 2022-07-15 15:15 UTC by JungDaewook

[구현 사항]
- 레이아웃을 제외한 스타일(색상, 글자 크기) 구현.

[중점 리뷰 사항]
- css 코드에서 중복된 코드가 많은데, 상위 태그에서 설정해줌으로써 코드 중복을 피할 수 있는 방법이 있는지
- 본인은 최대한 상위 태그에 설정하려고 노력했으나, 혹시 더 좋은 방법이 있는지 궁금

2022-07-15 15:17 UTC, JungDaewook commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "<div class = 'strikeAndRemoveButton'><input type = 'button' id = 'strikeButton' onclick = 'strikeTodoItem(\""+todoItemId+"\")' value = '완료'/><input type = 'button' id = 'remo
[설명]
삭제 버튼의 디자인을 구현하기 위해서 'removeButton' 이라는 id 부여

2022-07-15 15:18 UTC, JungDaewook commented on functionsOfTodoList.js
> +  todoItem.innerHTML += "<div class = 'strikeAndRemoveButton'><input type = 'button' id = 'strikeButton' onclick = 'strikeTodoItem(\""+todoItemId+"\")' value = '완료'/><input type = 'button' id = 'remo
[설명]
삭제 버튼의 디자인을 구현하기 위해서 'removeButton' 이라는 id 부여

2022-07-15 15:19 UTC, JungDaewook commented on Todo_List.html
> +                        <input type = 'button' id = 'removeAllButton' value = '전체 삭제' onclick = 'removeAllTodoItem()'/>
[설명]
디자인 구현을 위해 추가 버튼과 전체삭제 버튼에 id 부여

2022-07-15 15:20 UTC, JungDaewook commented
[질문]
커밋의 단위를 큼직큼직함 컨테이너들로 나눴는데 더 쪼개는 것이 좋을까요?

2022-07-15 15:36 UTC, JungDaewook reviewed
1. bodyContainer와 body 사이에 하얀색으로 margin이 잡히는 문제 해결
2. todoItem을 많이 추가했을 때 아래 부분에 bodyContainer의 설정이 해결되지 않는 문제 해
<img width="1728" alt="스크린샷 2022-07-16 오전 12 23 39" src="https://user-images.githubusercontent.com/40848888/179257391-cc73026e-0580-474b-b352-0532d3a091d2.png">
<img width="847" alt="스크린샷 2022-07-16 오전 12 25 32" src="https://user-images.githubusercontent.com/40848888/179257418-682f45a2-c19c-41ed-bd6a-11a7933ef8dd.png">
결

2022-07-18 14:09 UTC, unpo88 requested changes
@JungDaewook 

> css 코드에서 중복된 코드가 많은데, 상위 태그에서 설정해줌으로써 코드 중복을 피할 수 있는 방법이 있는지
> 본인은 최대한 상위 태그에 설정하려고 노력했으나, 혹시 더 좋은 방법이 있는지 궁금

[질문]
1. 현재 작성된 코드를 기준으로 중복된 코드는 어떠한 부분을 이야기하는 것일까요?
2. CSS 중복 제거를 위해 찾아본 자료가 있을까요? 있다면 어떤 자료를 살펴보았을까요?

2022-07-18 14:09 UTC, unpo88 commented on styleOfTodoList.css
> +
@JungDaewook 

이 부분은 개행이 들어간 이유가 있을까요?

2022-07-18 14:09 UTC, unpo88 commented on styleOfTodoList.css
> +
@JungDaewook 

이 부분은 개행이 들어간 이유가 있을까요?

2022-07-18 14:09 UTC, unpo88 commented on styleOfTodoList.css
> +
@JungDaewook 

이 부분도 개행이 들어간 이유가 있을까요?

2022-07-18 14:09 UTC, unpo88 commented on styleOfTodoList.css
> +
@JungDaewook 

이 부분은 개행이 들어간 이유가 있을까요?

2022-07-18 14:09 UTC, unpo88 commented on styleOfTodoList.css
> +
@JungDaewook 

여기도 개행이 들어간 이유가 있을까요?

2022-07-19 09:19 UTC, JungDaewook commented on styleOfTodoList.css
> +
[답변 / 질문]
가독성을 높이려는 목적으로 전체적인 레이아웃을 담당하는 코드와 세세한 스타일을 담당하는 코드를 분리하려고 개행을 넣었어요. 아래의 개행들도 같은 이유입니다. 혹시 잘못되거나 잘 사용하지 않는 방식일까요? 만약 잘못된 방식이라면 수정하도록 하겠습니다.

2022-07-19 09:19 UTC, JungDaewook commented on styleOfTodoList.css
> +
[답변]
가독성을 높이려는 목적으로 전체적인 레이아웃을 담당하는 코드와 세세한 스타일을 담당하는 코드를 분리하려고 개행을 넣었어요. 혹시 잘못되거나 잘 사용하지 않는 방식일까요?

2022-07-19 09:20 UTC, JungDaewook commented on styleOfTodoList.css
> +
[답변]
가독성을 높이려는 목적으로 전체적인 레이아웃을 담당하는 코드와 세세한 스타일을 담당하는 코드를 분리하려고 개행을 넣었어요. 혹시 잘못되거나 잘 사용하지 않는 방식일까요?

2022-07-20 15:31 UTC, JungDaewook commented on Todo_List.html
> -    <div class = "bodyContainer">
[코드 수정]
bodyContainer 제거

2022-07-20 15:31 UTC, JungDaewook commented on Todo_List.html
> -            <div class = "todoListNavContainer"></div>
[코드 수정]
todoListNavContainer 제거

2022-07-20 15:32 UTC, JungDaewook commented on Todo_List.html
> -            <div class = "todoListAdContainer"></div>
[코드 수정]
todoListAdContainer 제거

2022-07-20 15:33 UTC, JungDaewook commented on styleOfTodoList.css
> +    justify-content : center;
[코드 추가]
nav / ad 컨테이너가 없어서 가운데 정렬을 해주기 위한 코드 추가

2022-07-22 16:33 UTC, unpo88 commented on styleOfTodoList.css
> +
@JungDaewook 

[질문]

잘못되거나 잘 사용하지 않는 방식인지 혹은 잘 사용하는 방식인지를 찾아보려면 어떻게 찾아보면 좋을까요?

2022-07-22 16:33 UTC, unpo88 commented on Todo_List.html
> -    <div class = "bodyContainer">
@JungDaewook 

이렇게 모든 작업마다 코멘트를 달아놓은 이유가 있을까요?
리뷰어가 이 코멘트를 통해 어떤 정보를 얻기를 기대하는 것일까요?

`bodyContainer 제거`라는 정보는 코드에 나와있는 것을 그대로 이야기한 것 같은데
코멘트는 코드에 드러나지 않거나 특별한 부분에 대해서 리뷰를 받고 싶은 부분이 있거나
리뷰어가 이해하기 어려운 부분에 대해서 코멘트가 달려야할 것 같은데

이 경우에는 위에 제가 나열한 경우에 해당되는 것 같지 않아서요 🤔 
오히려 리뷰어에게 불필요한 정보처럼 느껴집니다.

2022-07-22 16:33 UTC, unpo88 commented on Todo_List.html
> -            <div class = "todoListNavContainer"></div>
@JungDaewook 

위 코멘트와 동일합니다.

2022-07-22 16:34 UTC, unpo88 commented on Todo_List.html
> -    <div class = "bodyContainer">
아래 코멘트가 달린것들을 보니 모두 동일하네요.

우선 Resolve 처리하겠습니다. 왜 그렇게 작성했는지, 어떠한 것을 기대했는지 설명 부탁드립니다 🙏

2022-07-22 16:34 UTC, unpo88 requested changes
@JungDaewook 

상단에 다양한 코멘트를 남겨놓았어요.

2022-07-22 17:39 UTC, JungDaewook commented on styleOfTodoList.css
>  }
[코드 수정 / 질문]
- 코드 수정
css 코드에서 많이 사용하는 방식으로 띄어쓰기를 수정했어요. 이유는 구글링을 해 봤는데 잘 안 나왔어요. 

- 질문
변수 같은 것을 할당 할때는 왼쪽의 변수와 오른쪽의 상수를 구분하기 위해 `int a = 3;`과 같이 등호의 왼쪽과 오른쪽에 띄어쓰기를 추가하는데, css의 경우에는 할당을 하는 것이 아닌 왼쪽의 속성 값(display)이 flex라는 것만 알면 되기 때문에 띄어쓰기를 : 의 오른쪽에만 추가하는 것이 맞나요?

2022-07-22 17:50 UTC, JungDaewook commented
> @JungDaewook
> 
> > css 코드에서 중복된 코드가 많은데, 상위 태그에서 설정해줌으로써 코드 중복을 피할 수 있는 방법이 있는지
> > 본인은 최대한 상위 태그에 설정하려고 노력했으나, 혹시 더 좋은 방법이 있는지 궁금
> 
> [질문]
> 
> 1. 현재 작성된 코드를 기준으로 중복된 코드는 어떠한 부분을 이야기하는 것일까요?
> 2. CSS 중복 제거를 위해 찾아본 자료가 있을까요? 있다면 어떤 자료를 살펴보았을까요?

[답변]
1. border-radius 과 같은 속성들은 같은 값을 가지는 요소들이 많아서 각 요소들의 스타일에 모두 들어가는 중복이 발생했어요.
2. CSS 중복 뿐만이 아니라 CSS 코드 작성 가이드라인에 대해 찾아보았어요. 
[https://velog.io/@rlatmdgns94/guide#:~:text=CSS%20%EC%9E%91%EC%84%B1%20%EA%B7%9C%EC%B9%99%20%2D%20%EC%B0%B8%EC%A1%B0,-%EC%84%A0%EC%96%B8(%EC%86%8D%EC%84%B1)%20%EC%88%9C%EC%84%9C&text=%EC%95%8C%ED%8C%8C%EB%B2%B3%20%EC%88%9C%EC%84%9C%EB%8C%80%EB%A1%9C%20%EC%86%8D%EC%84%B1%EC%9D%84,%EA%B0%80%EC%9E%A5%20%EB%A7%88%EC%A7%80%EB%A7%89%EC%97%90%20%EC%84%A0%EC%96%B8%ED%95%9C%EB%8B%A4.&text=CSS%20%EC%86%8D%EC%84%B1%EC%88%9C%EC%84%9C%EB%A5%BC%20%EC%95%8C%ED%8C%8C%EB%B2%B3%EC%88%9C%EC%9C%BC%EB%A1%9C%20%ED%95%9C%EB%8B%A4%EB%8B%88%20%EB%86%80%EB%9D%BC%EC%9B%A0%EB%8B%A4.](url)

2022-07-22 17:59 UTC, JungDaewook commented on Todo_List.html
> -    <div class = "bodyContainer">
[답변]
커밋을 살펴보니 코드가 통째로 삭제됐다가 추가된 것처럼 나타나 있어서 리뷰어가 바뀐 것을 파악하기 어려울 수도 있겠다는 판단 하에 세세하게 코멘트를 남겼어요.

지금 보니 저도 리뷰어가 충분히 코드를 보고 이해할 수 있을 것 같다는 생각이 들어요. 다음부터는 주의하도록 할게요!

2022-07-22 18:04 UTC, JungDaewook commented on styleOfTodoList.css
> +
[https://velog.io/@rlatmdgns94/guide](url)
[답변]
위의 링크에서 css 작성 가이드라인 자료를 찾아본 후 사용하지 않는 방식이라는 것을 알게 돼서 불필요한 개행을 아래 커밋에서 제거했어요.
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/04a016bec049441f15e27e24ee31d487d6dc824b

2022-07-27 15:21 UTC, JungDaewook commented
[코드 수정]
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/225e834134d3b89917b40289c0f3ab29dc629496
위 커밋으로 marker 위치 조정에 성공했어요.

2022-07-27 15:22 UTC, JungDaewook commented
[질문 / merge 여부]
이제 모든 코멘트에 대한 답변과 수정이 완료된 것 같은데 merge해도 될까요?

2022-07-30 07:06 UTC, JungDaewook commented
[리팩토링]
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/524934111e528f6d0a4a1acb2e403b969678cc5a

[코드 수정]
- 위 커밋에서 innerHTML 코드의 가독성을 위해 코드를 추가하고 수정했어요.

[세부 사항]
- 완료, 취소, 삭제 버튼의 innerHTML 내용을 반환하는 함수를 만들어 가로로 길었던 코드를 축소하고 중복되는 코드들을 함수로 대체했어요.

2022-07-30 23:23 UTC, JungDaewook commented on styleOfTodoList.css
> +    position: relative;
[질문]
position에 대한 충분한 조사가 있었나요?

2022-07-30 23:23 UTC, JungDaewook commented on styleOfTodoList.css
> +    margin-left: 10px;
[코멘트]
margin 과 margin-left 는 한번에 쓸 수 있지 않을까요?

2022-07-30 23:25 UTC, JungDaewook commented on styleOfTodoList.css
> +    list-style-position: inside;
[질문]
이 코드는 꼭 필요한 코드일까요?

2022-08-02 08:01 UTC, JungDaewook commented on styleOfTodoList.css
> +    margin-left: 10px;
[수정 완료]
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/4059c4f0cf224d32626bc94217cdf03af8bdbfac
위 커밋에서 축약했어요.

2022-08-02 08:29 UTC, JungDaewook commented on styleOfTodoList.css
> +    position: relative;
[답변]
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/389566187fd05814b4121ea3fe4a8eb0c0d7c52a
불필요한 코드라고 생각되어 위 커밋에서 삭제했어요.

2022-08-02 08:35 UTC, JungDaewook commented on styleOfTodoList.css
>      position: absolute;
[문제 발생 / 해결]

- [문제 상황]
`position: absolute`라고 설정하지 않으면 밑 사진과 같이 before 태그가 flex의 레이아웃에 참여하는 현상이 있었어요.
<img width="599" alt="스크린샷 2022-08-02 오후 5 27 20" src="https://user-images.githubusercontent.com/40848888/182329723-1063120f-eebf-4925-9ae7-27611eac7059.png">

- [해결]
`position: absolute`로 설정해주니 before 태그가 flex의 레이아웃에 참여하지 않아 밑 사진과 같이 의도한대로 구현할 수 있었어요.
<img width="581" alt="스크린샷 2022-08-02 오후 5 33 50" src="https://user-images.githubusercontent.com/40848888/182330377-98c59e41-0127-45d5-938c-62d16658248b.png">

- [참고 자료]
밑의 링크를 통해 position을 absolute로 설정해주면 해당 설정이 적용된 태그가 flex의 레이아웃에 참여하지 않는다는 사실을 알게 됐어요.
https://chenhuijing.com/blog/flexbox-and-absolute-positioning/#%F0%9F%A7%97%E2%80%8D%E2%99%80%EF%B8%8F

2022-08-02 09:28 UTC, JungDaewook commented on functionsOfTodoList.js
> +let todoItemId = returningTodoItemId();
[불필요한 코드 제거]
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/cb96fc33936590f3807a4a84ddc38fdebf0010bd
구현과정에서 나온 불필요한 코드를 실수로 남겨놓아서 위 커밋에서 제거했어요. 커밋을 남길 때 변경사항들을 다시 한번 확인하는 습관을 길러야겠다고 생각했어요.

2022-08-02 09:30 UTC, JungDaewook commented
[코드 수정]
https://github.com/JungDaewook/Todo-JavaScript/pull/16/commits/a86f387868c60f19fb399e747af37519f329bf7f

- [수정 사항]
버튼 관련 코드가 중복되는 문제를 위 커밋으로 해결했어요.
1. 버튼을 만들기 위한 innerHtml text를 div 태그로 감싸는 함수 구현
2. 함수 내에서 버튼을 만들기 위한 innerHtml text를 변수로 설정.

2022-10-07 07:39 UTC, merged