Add list
JungDaewook/Todo-JavaScript pull request #3
Opened 2022-03-18 17:06 UTC by JungDaewook

I finished third requirement addList.

2022-03-21 02:37 UTC, unpo88 requested changes
@JungDaewook 

코멘트 남겨놓았는데 확인 부탁드립니다~

2022-03-21 02:37 UTC, unpo88 commented on Todo_List.html
> +    <input type = 'text' id = 'addValue' />
@JungDaewook 

![image](https://user-images.githubusercontent.com/14287771/159197861-5e747af1-6477-4e48-9584-fc4170393e48.png)

해당 `input`이 나타내는 것이 스크린샷에서 표시한 영역으로 보이는데요.

`addValue`라는 `id`를 가지는 것 보다 의미상으로는 `Todo`를 입력하는 영역에 가까운 것 같아요.

`id`의 값을 `todoInputText`라는 조금 더 명시적인 이름으로 변경하는 것은 어떠한가요?

2022-03-21 02:37 UTC, unpo88 commented on addList.js
> +    const addValue = document.getElementById('addValue').value;
@JungDaewook 

상단의 코멘트에 맞추어서

``` javascript
const todoInputText = document.getElementById('todoInputText').value;
``` 

라는 코드로 변경하면 조금 더 직관적으로 어떤 행위인지 이해하는데 도움이 될 것 같습니다!

2022-03-21 02:37 UTC, unpo88 commented on addList.js
> +    li.setAttribute('id',addValue);
@JungDaewook 

[질문]

해당 `li`에 `id`값을 `set` 해준 이유가 무엇인가요?

2022-03-21 02:37 UTC, unpo88 commented on addList.js
> +    const li = document.createElement('li');
@JungDaewook 

`li`라는 네이밍보다 `todoItem`이라는 이름을 가지는것이 조금 더 이해하는데 가독성이 좋지 않을까요?

2022-03-21 02:37 UTC, unpo88 commented on Todo_List.html
> +    <ul id = 'list'></ul>
@JungDaewook 

`id`의 값을 `todoList`라는 네이밍으로 조금 더 직관적으로 변경해주는 것이 좋지 않을까요?

2022-03-21 02:37 UTC, unpo88 commented on Todo_List.html
> +    <input type = 'button' value = '추가' onclick = 'addList()' />
@JungDaewook 

`addList` 보다는 `addTodoItem`이라는 네이밍이 조금 더 직관적인 네이밍이지 않을까요?

2022-03-21 02:37 UTC, unpo88 commented on addList.js
> +    document.getElementById('list').appendChild(li);
@JungDaewook 

``` javascript
todoList = document.getElementById('list')
todoList.appendChild(li)
```

와 같은 형태로 코드를 바꾸는 것이 조금 더 직관적이지 않을까요?

2022-03-22 15:22 UTC, JungDaewook commented on Todo_List.html
> +    <input type = 'text' id = 'addValue' />
addValue -> todoInputText로 변경 완료

2022-03-22 15:22 UTC, JungDaewook commented on addList.js
> +    const addValue = document.getElementById('addValue').value;
변경완료

2022-03-22 15:23 UTC, JungDaewook commented on addList.js
> +    const li = document.createElement('li');
li -> todoItem으로 변경완료 (나타내는 것이 todolist에 들어갈 항목이었기 때문에 li라는 변수명보다는 todoItem이 더 적합하다고 판단)

2022-03-22 15:28 UTC, JungDaewook commented on addList.js
> +    document.getElementById('list').appendChild(li);
기존 코드보다 직관적이고 가독성이 좋다 판단되어서 변경 완료.

2022-03-22 15:28 UTC, JungDaewook commented on Todo_List.html
> +    <input type = 'button' value = '추가' onclick = 'addList()' />
함수명, js 파일명 변경완료, 브랜치명 변경예정

2022-03-22 15:29 UTC, JungDaewook commented on Todo_List.html
> +    <ul id = 'list'></ul>
list라는 너무 흔하고 보편적인 이름보다 todoList라는 네이밍이 더 직관적이라고 판단되어 변경완료.

2022-03-22 15:30 UTC, JungDaewook commented on addList.js
> +    li.setAttribute('id',addValue);
불필요한 코드라는 것을 인지하여 삭제 완료.

2022-03-27 12:35 UTC, merged