Modify that i missed
JungDaewook/Todo-JavaScript pull request #7
Opened 2022-03-27 13:37 UTC by JungDaewook

2022-04-01 14:48 UTC, unpo88 requested changes
@JungDaewook 

수정이 필요한 사항에 대해서 코멘트 남겨놓았습니다.

------------------------

**[추가 과제]**
아래 영상을 살펴보면 `input` 에 값을 입력하고, 추가를 눌렀을 때, `input` 값이 초기화되지 않고, 그대로 유지되는 경우가 있어요. 요것을 초기화해주려면 어떻게 해야할까요? 🤔 

https://user-images.githubusercontent.com/14287771/161287161-1b4eb952-4607-4449-a287-2024fe9a3270.mov

2022-04-01 14:48 UTC, unpo88 commented on Todo_List.html
> +        </style>
@JungDaewook 

해당 스타일은 아래 요구사항을 만족시키기 위해 작성된 코드로 보이는데요 🤔 

- “할 일 목록"을 보여줄 수 있는 **리스트**가 존재한다.
    - 할 일 목록은 최대 20개까지 입력 가능하다.

하지만, 해당 코드는 최대 20개 까지 입력이 가능하다가 아니라

"20개 이후의 리스트 항목을 숨김처리(`display: none`)한다"의 요구사항을 만족시키는 것 같아요.

실제로는, 20개 이후의 항목들이 생성되고 있습니다. 수정이 필요하지 않을까요?

2022-04-01 14:48 UTC, unpo88 commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
@JungDaewook 

간단한 가독성을 위해 다음과 같이 수정하면 더 좋지 않을까요?
- 개행문자 추가
- `todoInputText` -> `todoInputTextValue` 로 네이밍 수정

``` javascript
const todoInputTextValue = document.getElementById('todoInputText').value;
const todoItem = document.createElement('li');
const textNode = document.createTextNode(todoInputTextValue);

todoItem.appendChild(textNode);
todoList = document.getElementById('todoList');
todoList.appendChild(todoItem);
```

2022-04-15 15:27 UTC, JungDaewook commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
> @JungDaewook
> 
> 간단한 가독성을 위해 다음과 같이 수정하면 더 좋지 않을까요?
> 
> * 개행문자 추가
> * `todoInputText` -> `todoInputTextValue` 로 네이밍 수정
> 
> ```js
> const todoInputTextValue = document.getElementById('todoInputText').value;
> const todoItem = document.createElement('li');
> const textNode = document.createTextNode(todoInputTextValue);
> 
> todoItem.appendChild(textNode);
> todoList = document.getElementById('todoList');
> todoList.appendChild(todoItem);
> ```

[답변/수정완료/질문]

[답변]
[https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/0758b17c3c2cabeefe8317606e56bf445f9f1578]
위 커밋으로 수정완료하였습니다.

[질문]
혹시 'todoInputText' 에서 'todoInputTextValue' 로 바꾸는 것이 좋겠다고 한 이유가 입력값의 id인 'todoInputText' 와 헷갈릴까봐가 맞나요?

2022-04-15 15:58 UTC, JungDaewook commented on Todo_List.html
> +        </style>
> @JungDaewook
> 
> 해당 스타일은 아래 요구사항을 만족시키기 위해 작성된 코드로 보이는데요 🤔
> 
> * “할 일 목록"을 보여줄 수 있는 **리스트**가 존재한다.
>   
>   * 할 일 목록은 최대 20개까지 입력 가능하다.
> 
> 하지만, 해당 코드는 최대 20개 까지 입력이 가능하다가 아니라
> 
> "20개 이후의 리스트 항목을 숨김처리(`display: none`)한다"의 요구사항을 만족시키는 것 같아요.
> 
> 실제로는, 20개 이후의 항목들이 생성되고 있습니다. 수정이 필요하지 않을까요?

[답변/수정 완료]
[https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/efe91cb401ee7d41a10a0d9551e6de47d4aa3528](url)
위 커밋과 같이 html코드의 숨김처리 코드를 삭제하고 js 파일에서 list를 20개 이상 추가하지 못하도록 수정 완료.

2022-04-15 15:59 UTC, JungDaewook commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
[https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/efe91cb401ee7d41a10a0d9551e6de47d4aa3528
](url)

2022-04-15 16:01 UTC, JungDaewook commented on Todo_List.html
> +        </style>
[gh pr checkout 7](url)

2022-04-15 16:02 UTC, JungDaewook commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
[https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/0758b17c3c2cabeefe8317606e56bf445f9f1578](url)

2022-04-15 16:08 UTC, JungDaewook commented
[수정]

[https://github.com/JungDaewook/Todo-JavaScript/pull/7/files/efe91cb401ee7d41a10a0d9551e6de47d4aa3528..bd03bb5fde7778eee5163f137223e8788b2f7a1d](url)
입력창에 아무것도 입력하지 않아도 입력 버튼을 눌렀을 때 추가가 되는 문제 해결

2022-04-15 16:13 UTC, JungDaewook commented
> @JungDaewook
> 
> 수정이 필요한 사항에 대해서 코멘트 남겨놓았습니다.
> 
> **[추가 과제]** 아래 영상을 살펴보면 `input` 에 값을 입력하고, 추가를 눌렀을 때, `input` 값이 초기화되지 않고, 그대로 유지되는 경우가 있어요. 요것을 초기화해주려면 어떻게 해야할까요? 🤔
> 
>  2022-04-01.11.46.52.mov

[과제 달성]

[https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/a116e53f2e01fb2e248a08ebf87081818f2178d4](url)
위 커밋과 같이 입력값을 입력했을 때 입력창이 초기화되도록 구현.

2022-04-15 16:29 UTC, JungDaewook commented
[수정]

https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/a116e53f2e01fb2e248a08ebf87081818f2178d4

2022-04-15 16:30 UTC, JungDaewook commented
[수정]

https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/a116e53f2e01fb2e248a08ebf87081818f2178d4
위 커밋으로 같이 입력창에 아무것도 입력하지 않았을 때 list에 추가가 되는 문제 해결

2022-04-15 16:32 UTC, JungDaewook commented
> @JungDaewook
> 
> 수정이 필요한 사항에 대해서 코멘트 남겨놓았습니다.
> 
> **[추가 과제]** 아래 영상을 살펴보면 `input` 에 값을 입력하고, 추가를 눌렀을 때, `input` 값이 초기화되지 않고, 그대로 유지되는 경우가 있어요. 요것을 초기화해주려면 어떻게 해야할까요? 🤔
> 
>  2022-04-01.11.46.52.mov

[과제 달성]

https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/a116e53f2e01fb2e248a08ebf87081818f2178d4
위 커밋으로 입력값을 입력했을 때 입력창이 초기화되는 기능 구현.

2022-04-15 16:33 UTC, JungDaewook commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
> @JungDaewook
> 
> 간단한 가독성을 위해 다음과 같이 수정하면 더 좋지 않을까요?
> 
> * 개행문자 추가
> * `todoInputText` -> `todoInputTextValue` 로 네이밍 수정
> 
> ```js
> const todoInputTextValue = document.getElementById('todoInputText').value;
> const todoItem = document.createElement('li');
> const textNode = document.createTextNode(todoInputTextValue);
> 
> todoItem.appendChild(textNode);
> todoList = document.getElementById('todoList');
> todoList.appendChild(todoItem);
> ```

[답변/수정완료/질문]

[답변]

[답변/수정완료/질문]

[답변]
[https://github.com/https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/0758b17c3c2cabeefe8317606e56bf445f9f1578]
위 커밋으로 수정완료하였습니다.

[질문]
혹시 'todoInputText' 에서 'todoInputTextValue' 로 바꾸는 것이 좋겠다고 한 이유가 입력값의 id인 'todoInputText' 와 헷갈릴까봐가 맞나요?
위 커밋으로 수정완료하였습니다.

[질문]
혹시 'todoInputText' 에서 'todoInputTextValue' 로 바꾸는 것이 좋겠다고 한 이유가 입력값의 id인 'todoInputText' 와 헷갈릴까봐가 맞나요?

2022-04-15 16:38 UTC, JungDaewook commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
a116e53

2022-04-15 16:39 UTC, JungDaewook commented
[수정]

bd03bb5
위 커밋을 통해 입력창에 아무것도 없을 때 값이 입력되지 않게 수정.

2022-04-15 16:40 UTC, JungDaewook commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
> @JungDaewook
> 
> 간단한 가독성을 위해 다음과 같이 수정하면 더 좋지 않을까요?
> 
> * 개행문자 추가
> * `todoInputText` -> `todoInputTextValue` 로 네이밍 수정
> 
> ```js
> const todoInputTextValue = document.getElementById('todoInputText').value;
> const todoItem = document.createElement('li');
> const textNode = document.createTextNode(todoInputTextValue);
> 
> todoItem.appendChild(textNode);
> todoList = document.getElementById('todoList');
> todoList.appendChild(todoItem);
> ```

[답변/수정완료/질문]

[답변] 
0758b17
 위 커밋으로 수정완료하였습니다.

[질문] 
혹시 'todoInputText' 에서 'todoInputTextValue' 로 바꾸는 것이 좋겠다고 한 이유가 입력값의 id인 'todoInputText' 와 헷갈릴까봐가 맞나요?

2022-04-15 16:41 UTC, JungDaewook commented on Todo_List.html
> +        </style>
> @JungDaewook
> 
> 해당 스타일은 아래 요구사항을 만족시키기 위해 작성된 코드로 보이는데요 🤔
> 
> * “할 일 목록"을 보여줄 수 있는 **리스트**가 존재한다.
>   
>   * 할 일 목록은 최대 20개까지 입력 가능하다.
> 
> 하지만, 해당 코드는 최대 20개 까지 입력이 가능하다가 아니라
> 
> "20개 이후의 리스트 항목을 숨김처리(`display: none`)한다"의 요구사항을 만족시키는 것 같아요.
> 
> 실제로는, 20개 이후의 항목들이 생성되고 있습니다. 수정이 필요하지 않을까요?

[답변/수정 완료]
efe91cb
위 커밋과 같이 html코드의 숨김처리 코드를 삭제하고 js 파일에서 list를 20개 이상 추가하지 못하도록 수정 완료.

2022-04-15 16:43 UTC, JungDaewook commented
https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/efe91cb401ee7d41a10a0d9551e6de47d4aa3528#diff-191efbd1925221a4ac2fb2e430714b9072551a60c97d771637ca849ece21a626R1

2022-04-15 16:50 UTC, JungDaewook commented on Todo_List.html
> +        </style>
[추가수정사한]
js로 todoItem 개수가 20개 넘지 못하도록 구현을 했다고 생각을 했는데 이제 보니 삭제를 했을 때 todoItemCount 가 1씩 감소하도록 구현하지 않아서 그 부분도 수정 후 다시 replt 남길게요

2022-04-15 16:51 UTC, JungDaewook commented on Todo_List.html
> +        </style>
[추가수정사항]
js로 todoItem 개수가 20개 넘지 못하도록 구현을 했다고 생각을 했는데 이제 보니 삭제를 했을 때 todoItemCount 가 1씩 감소하도록 구현하지 않아서 그 부분도 수정 후 다시 reply 남길게요

2022-04-16 13:38 UTC, unpo88 commented on addTodoItem.js
> +  todoList.appendChild(todoItem);
@JungDaewook 

맞습니다~

2022-04-16 13:42 UTC, unpo88 commented on functionsOfTodoList.js
> +  }
@JungDaewook 

[적극 제안]

20과 같은 상수는 다음과 같이 상수로 선언해주는 것이 의미적으로 어떤 것을 하는지 이해하기 좋지 않을까요?

``` javascript
const MAX_TODO_ITEM_COUNT = 20
function addTodoItem() {
    ... 
    if (TodoItemCount >= MAX_TODO_ITEM_COUNT) {
        ...
    }
```

추가로 TodoItemCount 역시 상수이기 때문에

TODO_ITEM_COUNT와 같은 네이밍 규칙을 가져가는것이 어떠한가요?

2022-04-16 14:03 UTC, unpo88 commented on functionsOfTodoList.js
> +  }
@JungDaewook

[적극/제안]

여기도 마찬가지로 다음과 같이 행위로 표현해주는건 어떠한가요?

``` javascript
const isEmptyTodoInputTextValue = todoInputTextValue === ''

if (isEmptyTodoInputTextValue) {
    return ;
}
```

2022-04-16 14:05 UTC, unpo88 requested changes
@JungDaewook 

코멘트 남겨놓았고

@JungDaewook 

[적극/제안]

추가로 UX/UI 상, 20개가 넘었다거나, 빈 Text를 추가했을 때 그냥 추가가 안되면

사용자가 왜 추가가 안되는지 인지하기 어렵지 않을까요?

사용자가 인지하기 쉽게 하려면 어떻게 해야할까요?

2022-04-17 00:08 UTC, JungDaewook commented on functionsOfTodoList.js
> +  }
> @JungDaewook
> 
> [적극 제안]
> 
> 20과 같은 상수는 다음과 같이 상수로 선언해주는 것이 의미적으로 어떤 것을 하는지 이해하기 좋지 않을까요?
> 
> 그리고 다음과 같이 해당 조건을 변수로 나타내면 해당 행위를 이해하는데 조금 더 이해하기 쉽지 않을까요?
> 
> ```js
> const MAX_TODO_ITEM_COUNT = 20
> 
> ...
> 
> function addTodoItem() {
>     const isMaximumTodoItemCount = TodoItemCount >= MAX_TODO_ITEM_COUNT
>     ... 
>     if (isMaximumTodoItemCount ) {
>         ...
>     }
> ```
> 
> 추가로 TodoItemCount 역시 상수이기 때문에
> 
> TODO_ITEM_COUNT와 같은 네이밍 규칙을 가져가는것이 어떠한가요?

[제안 수용/리팩터링 브랜치 신규 생성 후 수정 예정]
리팩터링 관련된 부분으로 보이는데 제안을 수용하여 수정할 새로운 리팩터링 브랜치를 만들어서 수정하도록 할게요!

2022-04-17 00:08 UTC, JungDaewook commented on functionsOfTodoList.js
> +  }
> @JungDaewook
> 
> [적극/제안]
> 
> 여기도 마찬가지로 다음과 같이 행위로 표현해주는건 어떠한가요?
> 
> ```js
> const isEmptyTodoInputTextValue = todoInputTextValue === ''
> 
> if (isEmptyTodoInputTextValue) {
>     return ;
> }
> ```

[제안 수용/리팩터링 브랜치 신규 생성 후 수정 예정]
리팩터링 관련된 부분으로 보이는데 제안을 수용하여 수정할 새로운 리팩터링 브랜치를 만들어서 수정하도록 할게요!

2022-04-17 00:09 UTC, JungDaewook commented
> @JungDaewook
> 
> 코멘트 남겨놓았고
> 
> @JungDaewook
> 
> [적극/제안]
> 
> 추가로 UX/UI 상, 20개가 넘었다거나, 빈 Text를 추가했을 때 그냥 추가가 안되면
> 
> 사용자가 왜 추가가 안되는지 인지하기 어렵지 않을까요?
> 
> 사용자가 인지하기 쉽게 하려면 어떻게 해야할까요?

[제안 수용/리팩터링 브랜치 신규 생성 후 수정 예정]
리팩터링 관련된 부분으로 보이는데 제안을 수용하여 수정할 새로운 리팩터링 브랜치를 만들어서 수정하도록 할게요! 위 코멘트 두 개를 수정하면서 같이 반영하여 수정하도록 할게요!

2022-05-02 18:23 UTC, JungDaewook commented on Todo_List.html
> +        </style>
[추가수정완료]
https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/7cbd623e63d77c55b99a79e38d36279e10c49784
위 커밋으로 todoItem이 삭제 될 때마다 todoItemCount가 하나씩 줄어듦으로써 removeTodoItem함수와 삭제 기능이 정상적으로 작동하도록 수정 완료.

2022-05-03 03:56 UTC, JungDaewook commented
https://github.com/JungDaewook/Todo-JavaScript/pull/10#discussion_r852196496
https://github.com/JungDaewook/Todo-JavaScript/pull/10#discussion_r862473140
https://github.com/JungDaewook/Todo-JavaScript/pull/10#discussion_r862473200
refactoring1에서 다른 코멘트는 다 처리하였고 위의 세가지 코멘트만 확인해주시면 될 것 같아요. modifyThatImissed에서의 코멘트도 다 처리한 것 같은데 코멘트 남겨주실 부분이 있으면 더 남겨주시고 아니라면 merge하고 전체삭제 기능을 구현하면 될 것 같아요.

2022-05-03 04:33 UTC, unpo88 approved these changes
@JungDaewook 

코멘트 하나 추가로 남겨놓았습니다~

확인 부탁드립니다 🙏

2022-05-03 04:33 UTC, unpo88 commented on functionsOfTodoList.js
> +  }
@JungDaewook 

[필수]

`isEmptyTodoInputText`, `isBiggerThanMaxTodoItemCount` 는 `handleAddButton`에서만 사용되는 것으로 보이는데 맞을까요?

그렇다면, 응집도를 높이기 위해

[Comment](https://github.com/JungDaewook/Todo-JavaScript/pull/7#discussion_r851629218)에 남겨놓은 것처럼 함수가 아닌 변수로 선언하는것은 어떠한가요~?

해당 코멘트 반영하고 Merge 부탁드립니다 🙇

2022-05-03 06:18 UTC, JungDaewook commented on functionsOfTodoList.js
> +  }
[반영 완료/merge하기 전 최종 확인]
https://github.com/JungDaewook/Todo-JavaScript/pull/7/commits/f6d5be36996158e89519a95e5e79ca67037058d8
위 커밋으로 반영완료했는데 제가 원섭님의 의도대로 한 것이 맞는지 확인받고 싶어요.

2022-05-03 08:00 UTC, unpo88 commented on functionsOfTodoList.js
> +  }
@JungDaewook 

맞습니다~ 👍

2022-05-03 08:08 UTC, unpo88 approved these changes
LGTM

2022-05-03 08:52 UTC, merged